apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1 # number of instances you want
  selector:
    matchLabels: # just key value pair to match a lable
      app: client
  template:
    metadata:
      labels:
        app: client # this works together with the metadata
    spec:
      containers:
        - name: client
          image: hhsu15/client:latest
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv # thi will serve as the DNS name, within the node
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
