apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1 # number of instances you want
  selector:
    matchLabels: # just key value pair to match a lable
      app: moderation
  template:
    metadata:
      labels:
        app: moderation # this works together with the metadata
    spec:
      containers:
        - name: moderation
          image: hhsu15/moderation:latest
          # imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv # thi will serve as the DNS name, within the node
spec:
  selector:
    app: moderation
  type: ClusterIP
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
