apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 2 # number of instances you want
  selector:
    matchLabels: # just key value pair to match a lable
      app: posts
  template:
    metadata:
      labels:
        app: posts # this works together with the metadata
    spec:
      containers:
        - name: posts
          image: ms/posts:latest
          imagePullPolicy: Never
