apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1 # number of instances you want
  selector:
    matchLabels: # just key value pair to match a lable
      app: posts
  template:
    metadata:
      labels:
        app: posts # this works together with the metadata
    spec:
      containers:
        - name: posts
          image: hhsu15/posts:latest
          # imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
