apiVersion: skaffold/v4beta11
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: hhsu15/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
manifests:
  rawYaml:
    - ./infra/k8s/*
